services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: ${DB-USERNAME}
      POSTGRES_PASSWORD: ${DB-PASSWORD}
      POSTGRES_DB: postgres
  backend:
    container_name: backend
    image: xtramarcf/asset-management-be:latest
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DB-USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB-PASSWORD}
      KEY_ADMIN-PASSWORD: ${ADMIN-PASSWORD}
      APPLICATION_SECURITY_JWT_SECRET-KEY: ${JWT}
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    image: xtramarcf/asset-management-fe:latest
    depends_on:
      - backend
    ports:
      - "4200:4200"

