name: Pipeline backend

#Trigg
on:
  push:
    branches:
      - master
      - dev
    paths:
      - backend/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml


jobs:
  checkout:
    runs-on: self-hosted
    name: Checkout project
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  compile:
    runs-on: self-hosted
    name: Compile project
    needs: [ checkout ]
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Compile project
        run: |
          cd backend
          ./mvnw clean compile

  start-test-db:
    runs-on: self-hosted
    name: Start test db
    needs: [ checkout ]
    steps:
      - name: Run PostgreSQL Docker container
        run: |
          docker ps -q --filter "name=postgres-test" | ForEach-Object {docker stop $_; docker rm $_}
          docker run -d `
          --name postgres-test `
          -e POSTGRES_USER=username `
          -e POSTGRES_PASSWORD=password `
          -e POSTGRES_DB=postgres-test `
          -p 5432:5432 `
          --restart unless-stopped `
          postgres

  tests:
    runs-on: self-hosted
    name: Unit tests
    needs: [ start-test-db, compile ]
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Running unit Tests
        run: |
          cd backend
          ./mvnw clean test 


  build:
    runs-on: self-hosted
    name: Build backend
    needs: [ tests ]
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build backend
        run: |
          cd backend
          ./mvnw clean package

      - name: Verify Package
        run: |
          cd backend
          ./mvnw verify

  build-image:
    name: Build Docker Image
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: docker/backend/Dockerfile
          push: true
          tags: xtramarcf/asset-management-be:latest

  stop-test-db:
    name: Stop test db
    runs-on: self-hosted
    needs: [ build-image ]
    steps:
      - name: Stop and remove PostgreSQL Docker container
        run: |
          docker stop postgres-test
          docker rm postgres-test

  deploy:
    name: Deploy Backend
    runs-on: self-hosted
    needs: [ stop-test-db ]
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT }}

    steps:
      - name: Deploy
        run: |
          cd ../../asset-management/asset-management/docker
          docker-compose up -d